Api endpoint to create collectivity
etalab/formulaire-qf pull request #116
Opened 2024-08-28 13:26 UTC by JeSuisUnCaillou

Boom 15h27 !

Closes https://linear.app/pole-api/issue/API-3142/pouvoir-creer-une-collectivite-dans-fqf-via-api

2024-08-28 13:30 UTC, JeSuisUnCaillou commented
Gnagnagna le lint gnagnagna

2024-08-28 13:53 UTC, skelz0r requested changes
Ne rien renvoyer sur un 201 c'est un peu la violence quand même hein :D 

Au passage renvoyer un http code 409 conflict si l'entité existe déjà ça pourrait être pas mal (même si on peut s'en sortir avec les messages d'erreurs, ceux-ci peuvent changer en vrai..)

2024-08-28 13:53 UTC, skelz0r commented on app/controllers/api/application_controller.rb
> +      # Compare the tokens in a time-constant manner, to mitigate timing attacks.
```suggestion
```

le commentaire ne traduit absolument pas le code ici, c'est brainfuck++

2024-08-28 13:53 UTC, skelz0r commented on app/controllers/api/collectivities_controller.rb
> +      render json: {}, status: :created
A minima renvoyer le modèle pour pouvoir stocker les infos (genre .. l'id).

2024-08-28 15:32 UTC, JeSuisUnCaillou commented
Aba on a même pas de contrainte sur l'unicité du siret :/
Je rajoute ça.

2024-08-28 16:18 UTC, skelz0r requested changes
Juste le schema.db qui imo est issue d'un code d'une autre branche, faut revert cette partie. Le reste c'est OK pour moi.

2024-08-28 16:18 UTC, skelz0r commented on db/schema.rb
> +    t.index ["hubee_folder_id"], name: "index_shipments_on_hubee_folder_id", unique: true
Faut revert ça sinon ça peut faire des trucs bizarres en prod potentiellement (ou alors c'est un oubli d'avant ?)

2024-08-28 17:59 UTC, JeSuisUnCaillou commented on db/schema.rb
> +    t.index ["hubee_folder_id"], name: "index_shipments_on_hubee_folder_id", unique: true
Effectivement, ça vient de ma branche qui voulait rajouter des validations sur la présence de ces colonnes alors que c'est une feature qu'on les delete à la fermeture d'un dossier.

2024-08-29 07:36 UTC, skelz0r approved these changes
C'est OK.

Petite remarque pour une PR supplémentaire : le siret suit une règle précise de construction, ça serait bien d'harden sa validation.

Des fichiers relevant: https://github.com/etalab/data_pass/blob/develop/app/validators/siret_validator.rb
https://github.com/etalab/data_pass/blob/develop/app/models/organization.rb#L2

2024-08-29 07:40 UTC, JeSuisUnCaillou commented
> C'est OK.
> 
> Petite remarque pour une PR supplémentaire : le siret suit une règle précise de construction, ça serait bien d'harden sa validation.
> 
> Des fichiers relevant: https://github.com/etalab/data_pass/blob/develop/app/validators/siret_validator.rb https://github.com/etalab/data_pass/blob/develop/app/models/organization.rb#L2

On a un validateur de siret, il est pas suffisant ?

2024-08-29 07:44 UTC, skelz0r commented
> > C'est OK.
> > Petite remarque pour une PR supplémentaire : le siret suit une règle précise de construction, ça serait bien d'harden sa validation.
> > Des fichiers relevant: https://github.com/etalab/data_pass/blob/develop/app/validators/siret_validator.rb https://github.com/etalab/data_pass/blob/develop/app/models/organization.rb#L2
> 
> On a un validateur de siret, il est pas suffisant ? -> https://github.com/etalab/formulaire-qf/blob/main/app/validators/siret_validator.rb

oh my bad, vu que vous n'aviez pas de validation d'uniqueness j'en ai déduis qu'il n'y avait rien.

2024-08-29 07:45 UTC, merged