Feature/api 2889 faire la page daccueil
etalab/formulaire-qf pull request #12
Opened 2024-06-06 09:54 UTC by JeSuisUnCaillou

2024-06-06 12:20 UTC, skelz0r commented
https://github.com/etalab/formulaire-qf/pull/12/commits/76fd887fb7911c2c9bc1c817cad580fa68fb83c5

J'aurais tellement rien customisé perso :') (pour garder le dsfr au max)

2024-06-06 14:36 UTC, JeSuisUnCaillou commented
> J'aurais tellement rien customisé perso :') (pour garder le dsfr au max)

J'intègre au plus près du design, faut respecter le/la designer voyons :p

2024-06-06 14:45 UTC, JeSuisUnCaillou commented
@skelz0r Mais surtout j'ai pas trouvé de bullet list dans le DSFR

2024-06-06 15:09 UTC, JeSuisUnCaillou commented
Quelques screenshots

# Page d'accueil

![Screenshot from 2024-06-06 17-08-06](https://github.com/etalab/formulaire-qf/assets/6117264/951ba577-faca-4c9d-b717-8cdb6ff39801)

# Page de choix de commune

![Screenshot from 2024-06-06 17-08-21](https://github.com/etalab/formulaire-qf/assets/6117264/cb6feb3d-ddb5-49a0-b227-b1b602f770ef)

2024-06-07 07:45 UTC, jbfeldis requested changes
C'est bon pour moi à part le bug d'asset en env de production.

Il faudra garder en tête l'aspect accessibilité du service (sur la page d'accueil y'a pas trop de question j'ai l'impression).

Et je pense aussi qu'il faut challenger tout ce qui n'est pas dans le DSFR pour ne pas risquer de se faire piéger niveau mobile/accessibilité.

2024-06-07 07:45 UTC, jbfeldis commented on app/assets/stylesheets/application.css
> +  background-image: url("assets/fr--success-fill.svg");
l'image ne fonctionne pas en sandbox, je suppose que c'est soit le chemin (sans "assets" ptet non ?) ou plutôt une question de config

la branche est livrée en sandbox: https://sandbox.quotient-familial.services.api.gouv.fr/

2024-06-10 07:59 UTC, JeSuisUnCaillou commented on app/assets/stylesheets/application.css
> +  background-image: url("assets/fr--success-fill.svg");
Uuuugh :roll_eyes: 
Et c'est là que je regrette d'avoir customisé.

Je regarde ça demain, aujourd'hui je bosse sur aplypro

2024-06-10 08:42 UTC, skelz0r commented on app/assets/stylesheets/application.css
> +  background-image: url("assets/fr--success-fill.svg");
A toute fine utile https://github.com/etalab/data_pass/blob/develop/docs/design.md#installation-de-la-derni%C3%A8re-version-du-dsfr

2024-06-11 09:24 UTC, JeSuisUnCaillou commented on app/assets/stylesheets/application.css
> +  background-image: url("assets/fr--success-fill.svg");
Lol le problème c'était que le gitignore ignore `public/assets` :facepalm:

2024-06-11 09:27 UTC, skelz0r commented on app/assets/stylesheets/application.css
> +  background-image: url("assets/fr--success-fill.svg");
Versionner `public/assets` c'est clairement pas une bonne idée btw vu que c'est que du fichier +/- temporaire là dedans.

2024-06-11 10:17 UTC, jbfeldis approved these changes
💯

2024-06-11 10:19 UTC, jbfeldis commented
Petit squash des commits avant le merge ? C'est quoi votre point de vue là dessus ?

2024-06-11 10:27 UTC, skelz0r commented
Personnellement je fais des commits atomiques qu'on peut revert facilement, avec une CI green à chaque commit si possible. Donc je rebase/squash souvent les trucs logiques ensemble.

Après les gens font ce qu'ils veulent du moment que c'est clair.

2024-06-11 10:45 UTC, JeSuisUnCaillou commented
je vais garder des commits atomiques au mieux, mais je pense qu'il y a quelques squashs à faire pour ça

2024-06-11 10:49 UTC, merged