Feature/api 2893 bouton france connect
etalab/formulaire-qf pull request #16
Opened 2024-06-11 15:41 UTC by JeSuisUnCaillou

2024-06-11 15:43 UTC, JeSuisUnCaillou commented
@jbfeldis je saisis pas pourquoi en test j'arrive pas à passer sur france connect alors que ça marche en dev.

J'ai un `No route matches [GET] "/api/v1/authorize"`, ça te parle ? :thinking:

2024-06-11 16:05 UTC, jbfeldis commented
Je suppose que c'est un manque de config de l'env de test, mais tu devrais stub d'ailleurs pour faire passer les tests, parce que là webmock doit se plaindre non (ou c'est qu'il n'arrive pas jusque là 🤔) ?

2024-06-13 14:00 UTC, JeSuisUnCaillou reviewed
Je n'ai pas pu écrire de tests d'acceptance pour le flow après le bouton FranceConnect.

Pluiseurs choses que je n'ai pas comprises :
1. Le mock d'OmniAuth dans [france_connect_steps.rb](https://github.com/etalab/formulaire-qf/blob/feature/api-2893-bouton-france-connect/features/step_definitions/france_connect_steps.rb) requiert une route `/api/v1/authorize` _dans nos routes_, alors que selon [la doc FC](https://partenaires.franceconnect.gouv.fr/images/schemas/seq-auth.png) c'est plutôt censé être une route chez eux.
2. Si on rajoute quand même [cette route](https://github.com/etalab/formulaire-qf/blob/feature/api-2893-bouton-france-connect/config/routes.rb/#L8) alors effectivement on arrive à passer le bouton franceconnect, mais on se retrouve avec un nouveau problème: la session n'est jamais remplie en test. ([cette ligne](https://github.com/etalab/formulaire-qf/blob/feature/api-2893-bouton-france-connect/app/controllers/collectivities_controller.rb/#L9) ne fait rien)
3. En essayant la gem [rack_session_access](https://github.com/railsware/rack_session_access) j'arrivais à setup une session (même si pas pratique par ce qu'on ne peut pas le faire au mileu du flow), mais je perdait la session une fois passé par FranceConnect. 

Donc flip table, je clean ma PR et je soumet à la review sans tests d'acceptance pour le moment.

2024-06-13 14:50 UTC, jbfeldis commented
On s'est bien pris la tête sur ce setup qui semble pourtant basique

On n'a pas réussi à mock omniauth correctement (et on n'a pas trouvé de trace simple de comment faire spécifiquement pour omniauth_openid_connect) et du coup ça donne des résultats qui n'ont pas de sens 

Par exemple cette histoire d'avoir un requête de GET en local (sur l'url de FC !) /v1/authorize alors que c'est une requête qui devrait être complètement côté FC (et du coup ça expliquerait le problème de session vide vu qu'on est plus sur le bon domaine)

Mais... ce n'est que partie remise ⚔️

2024-06-13 15:40 UTC, jbfeldis requested changes

2024-06-13 15:40 UTC, jbfeldis commented on app/controllers/collectivities_controller.rb
> +  before_action :set_collectivity, only: %i[select show]
Je laisse un commentaire ici mais c'est plutôt global.

J'aurais bien vu `Current.collectivity` remplacer `Current.recipient` et potentiellement être setup dans application_controller (enfin dans l'interactor qui setup Current)

On pourrait s'en sortir partout avec un setup environ comme ça non ? 
```ruby
session[:collectivity_id] ||= params[:id] # ptet garder collectivity_id ?
Current.collectivity = Collectivity.find_by!(siret: session[:collectivity_id])`
```
(avec éventuellement un objet vide dans les cas ou y'a pas de collectivity pour pas ajouter des conditions dans les vues)

2024-06-13 15:40 UTC, jbfeldis commented on app/controllers/sessions_controller.rb
> +    result = GetFamilyQuotient.call(recipient: Current.recipient, user: Current.user)
Du coup ici `Current.recipient` ça ne doit plus contenir la bonne info (ptet que ça explique l'erreur à la recup du QF)

2024-06-13 15:40 UTC, jbfeldis commented on app/controllers/collectivities_controller.rb
> +  before_action :set_collectivity, only: %i[select show]
Et du coup on pourrait utiliser `Current.collectivity` partout ce qui serait plutôt agréable

2024-06-13 15:40 UTC, jbfeldis commented on app/controllers/shipments_controller.rb
> +    hubee_recipient = HubEE::Recipient.new(siren: @collectivity.siret, branch_code: "04107")
On en a parlé et c'est un détail mais j'ai introduit `siren` et `siret`... il faudra harmoniser en follow up 🤦

2024-06-13 16:56 UTC, jbfeldis commented
J'ai rebase et ajouté un commit qui fixe la cinématique et `push --force-with-lease`, y'a pas bcp de changements donc tu pourras écraser (mais comme ça je peux tester la sandbox aussi)

2024-06-14 12:02 UTC, JeSuisUnCaillou commented on app/controllers/collectivities_controller.rb
> +  before_action :set_collectivity, only: %i[select show]
Ah oui j'avoue, j'ai pas été jusque là par fatigue, mais je suis tout à fait d'accord avec la suggestion.

2024-06-14 12:03 UTC, JeSuisUnCaillou commented on app/controllers/sessions_controller.rb
> +    result = GetFamilyQuotient.call(recipient: Current.recipient, user: Current.user)
Effectivement

2024-06-18 08:13 UTC, JeSuisUnCaillou commented on app/controllers/sessions_controller.rb
> +    result = GetFamilyQuotient.call(recipient: Current.recipient, user: Current.user)
plutôt https://github.com/etalab/formulaire-qf/blob/feature/api-2893-bouton-france-connect/app/controllers/sessions_controller.rb/#L38

2024-06-18 08:17 UTC, JeSuisUnCaillou commented on app/controllers/shipments_controller.rb
> +    hubee_recipient = HubEE::Recipient.new(siren: @collectivity.siret, branch_code: "04107")
A voir dans une autre PR

2024-06-18 08:50 UTC, JeSuisUnCaillou commented on app/controllers/collectivities_controller.rb
> +  before_action :set_collectivity, only: %i[select show]
J'ai utilisé le Current.collectivity partout sanf dans le `CollectivityController`, par ce que comme ici le param est `:id` par convention, je préfère pas dire à mon `SetupCurrentData` d'aller chercher le siret dans `params[:id]` sinon il va probablement faire de la merde sur le show d'un shipment (qui aura un id de shipment dans `params[:id]`)

2024-06-18 09:18 UTC, JeSuisUnCaillou commented
Quelle collab' cette PR n'empêche :smile:

2024-06-18 10:12 UTC, jbfeldis commented on app/controllers/sessions_controller.rb
> +    url = "https://fcp.integ01.dev-franceconnect.fr/api/v1/logout?id_token_hint=#{id_token_hint}&post_logout_redirect_uri=#{fc_logout_callback_url}"
purée, j'ai oublié de bouger l'url dans la config, à faire sur une PR de follow up

2024-06-18 10:13 UTC, jbfeldis commented on app/controllers/sessions_controller.rb
> +    result = GetFamilyQuotient.call(recipient: @collectivity.siret, user: Current.user)
du coup tu peux utiliser `Current.collectovity` au lieu de `@collectivity` partout non ?

2024-06-18 10:13 UTC, jbfeldis commented on app/controllers/sessions_controller.rb
> +    @collectivity = Current.collectivity
et du coup en utilisation `Current.collectivity` y'a plus besoin de ça

2024-06-18 10:18 UTC, jbfeldis commented on config/routes.rb
> +  # get "/api/v1/authorize", to: "sessions#create"
ça on peut virer du coup

2024-06-18 10:21 UTC, jbfeldis commented on app/views/collectivities/show.html.erb
> +  <%= simple_format t('pages.shipments.banner.text', label: @collectivity.name, code_cog: @collectivity.code_cog), { }, wrapper_tag: 'span' %>
J'ai un peu la même remarque ici : est-ce qu'on ne basculerait pas tout sur `Current.collectivity` ?

Vu que c'est vraiment lié à ta "session en cours" est-ce que ça vaut le coup que le controller prépare cette donnée pour la vue ?

2024-06-18 10:22 UTC, jbfeldis commented on features/step_definitions/france_connect_steps.rb
> +  OmniAuth.config.test_mode = true
🤦 et 🎉 en même temps !

2024-06-18 10:43 UTC, jbfeldis approved these changes

2024-06-18 10:48 UTC, merged