Feature/api 2975 integrer les cgu et la FAQ
etalab/formulaire-qf pull request #37
Opened 2024-06-25 16:04 UTC by JeSuisUnCaillou

2024-06-26 17:15 UTC, jbfeldis requested changes
J'avoue que je n'ai pas relu les CGUs sauf vérification des liens.

C'est top, gg @JeSuisUnCaillou et @DorineLam

2024-06-26 17:15 UTC, jbfeldis commented on app/views/home/cgu_administrations.html.erb
> +	<p>Le <strong>Formulaire QF</strong> est ouvert à tous les <strong>Usagers</strong> effectuant une démarche pour obtenir la tarification sociale d&#39;un service de l&#39;<strong>Administration</str
```suggestion
	<p>Le <strong>Formulaire QF</strong> est ouvert à tous les <strong>Usagers</strong> effectuant une démarche pour obtenir la tarification sociale d&#39;un service de l&#39;<strong>Administration</strong>, si cette dernière, <strong>l&#39;Administration</strong>, a mis en place le <strong>Service</strong> et s&#39;est engagée à en respecter les <a href="/cgu_administrations">CGU</a>.</p>
```

ça devrait pointer sur la même page ou c'est moi qui ne comprends pas le sens de la phrase ? (du coup faut il enlever le lien ?)

2024-06-26 17:15 UTC, jbfeldis commented on app/views/home/cgu_administrations.html.erb
> +	<p>La liste des <strong>Administrations* habilitées à proposer ce </strong>Service<strong> via le </strong>Formulaire QF<strong> à ses </strong>Usagers** est disponible depuis <a href="/collectiviti
petits soucis de balises strong et "*" qui se baladent j'ai l'impression

2024-06-26 17:15 UTC, jbfeldis commented on app/views/home/faq.html.erb
> +      <li>effectuant une démarche auprès collectivité qui a mis en place le service. La liste de ces collectivités est disponible depuis le menu déroulant de <a href="/collectivities">cette page</a>.
```suggestion
      <li>effectuant une démarche auprès d'une collectivité qui a mis en place le service. La liste de ces collectivités est disponible depuis le menu déroulant de <a href="/collectivities">cette page</a>.</li>
```

(c'est ptet juste que je ne sais pas lire des phrases bien tournées :sweat_smile:)

2024-06-26 17:15 UTC, jbfeldis commented on app/views/home/faq.html.erb
> +      A posteriori et ce, jusqu'à ce que vous ne soyez plus concerné par la démarche : la réutiliation de vos données d'identité par la collectivité pour mettre à jour vos données de quotient familia
```suggestion
      A posteriori et ce, jusqu'à ce que vous ne soyez plus concerné par la démarche : la réutilisation de vos données d'identité par la collectivité pour mettre à jour vos données de quotient familial et de composition familiale pour vous attribuer un tarif au plus près de votre situation.
```

2024-06-26 17:31 UTC, DorineLam commented on app/views/home/cgu_administrations.html.erb
> +	<p>Le <strong>Formulaire QF</strong> est ouvert à tous les <strong>Usagers</strong> effectuant une démarche pour obtenir la tarification sociale d&#39;un service de l&#39;<strong>Administration</str
Je sais plus haha 😅

2024-06-26 17:34 UTC, DorineLam commented on app/views/home/cgu_administrations.html.erb
> +	<p>Le <strong>Formulaire QF</strong> est ouvert à tous les <strong>Usagers</strong> effectuant une démarche pour obtenir la tarification sociale d&#39;un service de l&#39;<strong>Administration</str
je l'ai enlevé car inutile en effet

2024-06-26 17:36 UTC, DorineLam commented on app/views/home/cgu_administrations.html.erb
> +	<p>La liste des <strong>Administrations* habilitées à proposer ce </strong>Service<strong> via le </strong>Formulaire QF<strong> à ses </strong>Usagers** est disponible depuis <a href="/collectiviti
Bien vu !

2024-06-27 09:43 UTC, JeSuisUnCaillou commented on app/views/collectivities/_show_banner.html.erb
> +  <%= render partial: "shared/banner_duration_and_link", duration: duration %>
ah oui bien vu, j'ai dû virer ça en refactorisant

2024-06-27 12:55 UTC, jbfeldis approved these changes

2024-06-27 13:43 UTC, merged