Stocke les donnees dans hubee
etalab/formulaire-qf pull request #4
Opened 2024-05-23 10:01 UTC by jbfeldis

2024-05-23 15:16 UTC, jbfeldis commented
* **#4** 👈
* **#3**
* **#2** 
* **#1** 
* `main`

2024-05-24 07:20 UTC, skelz0r commented on app/controllers/claims_controller.rb
> +      Rails.logger.debug "Noïce"
👌

2024-05-24 08:07 UTC, skelz0r requested changes
Vu la taille de la PR j'ai surement loupé des trucs, on verra à la 2e review.

Pour moi y'a 2 gros points:

1. Le naming de l'organizer d'HubEE qui pour moi est pas assez précis (tout est dans le commentaire) ;
2. Le `recipient` qui semble représenté 2 choses différentes dans le code à clarifier.

Le reste c'est du détails

2024-05-24 08:07 UTC, skelz0r commented on spec/interactors/hubee/create_folder_spec.rb
> +RSpec.describe Hubee::CreateFolder, type: :organizer do
Un bon `it { is_expected.to be_a_success }`

(et d'ailleurs je me rends compte que tu ne l'as mis nul part)

2024-05-24 08:07 UTC, skelz0r commented on spec/interactors/hubee/mark_folder_complete_spec.rb
> +  end
```suggestion
  describe ".call" do
    subject(:interactor) { described_class.call(**params) }
  
    let(:folder) { double(Hubee::Folder, id: folder_id) }
    let(:folder_id) { "folder_id" }
    let(:params) do
      {
        folder:,
        session:,
      }
    end
    let(:session) { double(Hubee::Api) }

    it "marks the folder complete" do
      expect(session).to receive(:mark_folder_complete).with(folder_id: folder_id)
      interactor
    end
  end
```

Plus logique imo de faire

```ruby
describe '.method' do
  subject { described_class.method }
end
```

Cela s'applique partout ailleurs btw.

2024-05-24 08:07 UTC, skelz0r commented on spec/interactors/store_quotient_familial_spec.rb
> +RSpec.describe StoreQuotientFamilial, type: :organizer do
Même remarque que pour l'autre organizer -> un bon gros test E2E serait potentiellement le bienvenue.

2024-05-24 08:07 UTC, skelz0r commented on spec/models/hubee/attachment_spec.rb
> +RSpec.describe Hubee::Attachment do
Je me serais pas fait chié ici et j'aurais juste testé que la factory marche (ce qui teste +/- moins tout ce qu'il y a en dessous). Ce qui est important c'est que les tests fonctionnels passent, les attributs du modèle c'est peu important imo.

A la limite les 2 instances méthodes, mais honnêtement c'est peu important à mon sens.

Cette remarque est valide pour tous les autres modèles.

2024-05-29 15:06 UTC, jbfeldis commented on app/models/current.rb
> +  attribute :user, :quotient_familial, :recipient
C'est pas clair et en en parlant ensemble ça semblait indiquer qu'il fallait faire bouger ce "recipient" en "collectivité" ou "commune" mais en regardant la doc api-part on utilise "recipient" partout donc... est-ce que ça vaut le coup d'avoir un nom différent dans ce projet ?

2024-05-29 15:10 UTC, skelz0r commented on app/models/current.rb
> +  attribute :user, :quotient_familial, :recipient
Il faut 2 noms différents dans le codebase vu que ce sont 2 choses différentes. Ici il s'agit de quoi ? Si c'est un siret de service public tu peux mettre `service_public_siret`, et on fera le call sur API P avec `recipient: service_public_siret` au moins ça sera clair++

2024-06-03 08:06 UTC, jbfeldis commented on app/interactors/hubee/prepare_folder.rb
> +    # HubEE's portal view greps 13 chars after two dashes
C'était pas hyper clair (aussi parce que c'est pas clair globalement mais sans le bon format ça ne s'affiche pas correctement dans le portail HubEE :D), j'ai amélioré mais je vais le laisser parce que je pense que ça pourrait facilement passer à la trappe.

2024-06-03 08:29 UTC, jbfeldis commented on spec/models/hubee/attachment_spec.rb
> +RSpec.describe Hubee::Attachment do
Ouais, je vois ce que tu veux dire, mais j'avais pas de factory à la base.

Mais bon, qui peut le plus peut le moins et si ça devient des modèles un peu plus costaud ça pourra toujours faciliter.

2024-06-03 08:32 UTC, jbfeldis commented on app/models/pivot_identity.rb
>      @data[:recipient] = recipient
C'est la "commune" à laquelle l'usager veut transmettre son QF.

Donc c'est quoi le terme métier qui va bien ? "commune", "collectivité", autre ?
(je vais ajouter la BDD de ces objets aujourd'hui je pense donc autant en profiter !)

2024-06-03 09:16 UTC, skelz0r commented on app/models/pivot_identity.rb
>      @data[:recipient] = recipient
> Donc c'est quoi le terme métier qui va bien ? "commune", "collectivité", autre ?

Je pense que tu peux calquer sur la ressource où tu vas récupérer cette info (api geo je suppose ?). C'est un code postal ? Code insee ? Tu as des exemples ? Parce que là le mieux que j'ai c'est `commune_or_collectivite` (ce qui est pas ouf)

2024-06-03 10:04 UTC, jbfeldis commented on app/models/pivot_identity.rb
>      @data[:recipient] = recipient
Je suppose que le service est plutôt réservé aux communes mais "collectivité" ça englobe plus de possibilités.

Et cette info va venir de... ah ah, bonne question. Un bridge datapass ça serait, à terme, la bone façon pour industrialiser ça non ?

En gros il me faut le "nom" à afficher à l'utilisateur, le siret, les infos HubEE (a priori le siret et le code postal ou COG, je me note de vérifier) et de la "config" sous une forme à définir (éditeur pour le webhook, fonctionnalité de mise à jour auto, whatever).

2024-06-03 10:16 UTC, skelz0r commented on app/models/pivot_identity.rb
>      @data[:recipient] = recipient
Je vois que ça vient d'un param dans ton app (`ApplicationController`). Cela implique que tu te balades avec un get param `recipient` partout dans ton app.

imo ça n'a pas lieu d'être stocké dans `PivotIdentity` (ce qui n'a pas de sens je trouve, cela n'a rien à voir avec l'identité pivot).

Si je comprends bien le code ce `recipient` est/va être utilisé pour taper sur API Particulier. Si c'est le cas il faut que ça soit un siret.

Après si j'ai bien suivi on va donner un lien de formulaire à chaque commune, du coup ça serait un truc du genre `https://qf.whatever.gouv.fr/formulaire?siret=<siret>` (ou tout autre moyen d'identifier une collectivité pour lookup son siret derrière), de là imo tu stores ça en session, et tu le réinjectes dans `ClaimsController#quotient_familial`. D'ailleurs ici je ferai aussi les checks suivants :
1. Si pas de params `siret` -> erreur ;
2. Si `siret` n'est pas un siret valide -> erreur

2024-06-03 10:22 UTC, jbfeldis commented on app/models/pivot_identity.rb
>      @data[:recipient] = recipient
Oui, c'est exactement ça, il ne devrait en effet pas être là, je vais reprendre cet objet PivotIdentity qui ne va pas et c'est le plan de garder le "recipient" dans la session :ok_hand: 

Oui, c'est pourça qu'il s'appelle "recipient", ça semblait la norme sur API Particulier.
Le param/clé de session peut devenir "siret", ce qui est plus lisible.

Et du coup... le modèle/BDD "commune" ou "collectivité" ?

2024-06-04 16:05 UTC, skelz0r approved these changes
Vu en DM pour valider, ship it, iterate later

2024-06-04 16:22 UTC, jbfeldis commented on lib/hubee/api.rb
> +class Hubee::Api
Noté dans linear ;)

2024-06-04 16:23 UTC, merged