no duplicated references
etalab/formulaire-qf pull request #64
Opened 2024-07-03 14:12 UTC by JeSuisUnCaillou

Closes https://linear.app/pole-api/issue/API-3090/verifier-quune-reference-generee-nexiste-pas-deja

2024-07-03 14:21 UTC, JeSuisUnCaillou commented
Je pige pas l'erreur en test. Déjà chez moi je l'ai pas. Et puis oui effectivement j'ai ajouté une contrainte de DB sur reference not null, mais c'est _justement_ ce que cette ligne teste, alors je vois pas pourquoi il râle.

2024-07-03 14:27 UTC, JeSuisUnCaillou commented
Ah c'est bon j'ai compris je pense

2024-07-03 15:16 UTC, skelz0r requested changes
Cf mon gros com, je pense que ça serait mieux de cette façon là en terme de responsabilité.
D'ailleurs en y pensant si on pousse le vice, on pourrait carrément utiliser pg pour générer cette valeur.

2024-07-03 15:16 UTC, skelz0r commented on app/models/shipment.rb
> +  end
Globalement je pense que la génération de cette référence devrait juste être gérée dans le model. Délégué ça dans un interactor c'est pas ouf, même dans une factory je trouve ça peut robuste.

Ma propale:

```suggestion
  validates :reference, presence: true, uniqueness: true
  after_initialize :affect_reference

  def affect_reference
    loop do
      self[:reference] ||= SecureRandom.hex[0...13].upcase
      break if Shipment.where(reference: self[:reference]).none?
    end
  end
```

Plusieurs remarques: 
1. Y'a une loop pour être sûr que la ref n'existe pas (en pratique ça fera qu'une loop ofc)
2. Y'a un lazy `||=`, comme ça ça peut se setup à l'initilization

Ça permet de sortir la logique de build dans ton `PrepareQuotientFamilialHubEEFolder` (qui de loin a clairement trop de respo en vrai).

2024-07-03 15:16 UTC, skelz0r commented on spec/factories/shipments.rb
> +    reference { "AAAAAAAAAAAAA" }
je ferai une séquence ici, ta reference ayant une contrainte d'unicité ta factory va planter dès le 2eme create

```suggestion
    reference
```

et plus haut:

```ruby
sequence(:reference) { |n| n.to_s }
```

(btw ici je vois qu'il n'y a aucune contrainte de longueur d'où ma dummy sequence)

2024-07-03 15:16 UTC, skelz0r commented on spec/interactors/prepare_quotient_familial_hubee_folder_spec.rb
> +      allow(SecureRandom).to receive(:hex).and_return("abcdef1234567")
pourquoi ce changement ?

2024-07-04 09:05 UTC, JeSuisUnCaillou commented on app/models/shipment.rb
> +  end
Ouais assez d'accord. Faut que je revoie les interactors qui ont été faits alors, par ce qu'en l'état, il crée le shipment après la data à envoyer, là faudrait que je build le shipment d'abord ça serait mieux.

2024-07-04 09:06 UTC, JeSuisUnCaillou commented on spec/factories/shipments.rb
> +    reference { "AAAAAAAAAAAAA" }
Je vais ajouter une contrainte de longueur tiens

2024-07-04 09:07 UTC, JeSuisUnCaillou commented on spec/interactors/prepare_quotient_familial_hubee_folder_spec.rb
> +      allow(SecureRandom).to receive(:hex).and_return("abcdef1234567")
pas faux, je remet.

2024-07-04 09:48 UTC, JeSuisUnCaillou commented on app/models/shipment.rb
> +  end
Alors ta loop, elle génère tout le temps le même hex (du moins en test). Du coup j'ai gardé mon approche récursive.
Et il faut aussi lui dire de pas `affect_reference` si `persisted?` (j'ai galéré avec ça, j'avais des trucs randoms tout le temps je devenais fou)

Mais j'ai du coup changé la logique pour donner la respo de la génération de la référence au shipment.

2024-07-04 12:06 UTC, skelz0r reviewed
Quelques remarques mais rien de bloquant. Re-request moi après résolution/correction je validerai.

2024-07-04 12:06 UTC, skelz0r commented on spec/factories/shipments.rb
>    factory :shipment do
Je suis dubitatif que cette factory soit valide vu les contraintes sur l'attribut `reference`.
Je serai d'avis de faire une factory valide. J'ai d'ailleurs l'habitude de systématiquement tester les factories:

```ruby
it 'has valid factories' do
  expect(build(:shipment)).to be_valid
end
```

Là limite la factory n'a pas d'intérêt (autant initialiser directement le modèle)

2024-07-04 12:06 UTC, skelz0r commented on spec/models/shipment_spec.rb
> +  end
Cf mon com sur la factory, c'est qu'un avis mais je trouve que les validations shoulda matcher n'apporte rien fonctionnellement, je trouve ça mieux de vérifier que la factory est valide (et donc manipulable en dehors de la couche modèle).

2024-07-04 12:31 UTC, JeSuisUnCaillou commented on app/models/shipment.rb
> +  end
le after_initialize s'execute quand tu instancie un record persisté via un `Shipment.last` par exemple.

J'ai découvert ça avec mes tests, et j'ai été vérifier dans la doc : https://guides.rubyonrails.org/active_record_callbacks.html#after-initialize-and-after-find

2024-07-04 12:31 UTC, JeSuisUnCaillou commented on app/models/shipment.rb
> +  end
ok pour le `.any?`

2024-07-04 12:35 UTC, skelz0r commented on app/models/shipment.rb
> +  end
Ah bah oui c'est logique en fait

2024-07-04 12:41 UTC, skelz0r commented on spec/factories/shipments.rb
>    factory :shipment do
Et en fait je suis teubé vu qu'on génère le reference plus haut

2024-07-04 12:41 UTC, skelz0r approved these changes

2024-07-04 12:43 UTC, merged