Link shipments and collectivities for stats and debug
etalab/formulaire-qf pull request #68
Opened 2024-07-04 13:49 UTC by JeSuisUnCaillou

Closes https://linear.app/pole-api/issue/API-3123/link-shipments-and-collectivities-in-db

2024-07-04 13:51 UTC, JeSuisUnCaillou commented
Reste un sujet : qu'est-ce qu'on fait des (5) shipments existants sans collectivity en prod ? :thinking:

2024-07-08 13:30 UTC, jbfeldis requested changes

2024-07-08 13:30 UTC, jbfeldis commented on spec/jobs/populate_hubee_sandbox_job_spec.rb
> +      allow(UploadQuotientFamilialToHubEE).to receive(:call).and_call_original
je l'avais complètement oublié celui là 🙆‍♂️

2024-07-08 13:30 UTC, jbfeldis commented on app/models/shipment.rb
> +  belongs_to :collectivity
alors pour ton point sur les shipments existants il faudrait séparer avec une 2e PR, ici il faudrait donc `optional: true` dans cette PR (à enlever dans le follow up post migration)

2024-07-08 13:30 UTC, jbfeldis commented on db/migrate/20240704131031_add_collectivity_id_to_shipments.rb
> +    add_reference :shipments, :collectivity, foreign_key: true
j'ai pas le truc en tête mais il me semble que laissé comme ça ça permet à la colonne d'être vide right ?

2024-07-08 14:37 UTC, JeSuisUnCaillou commented on app/models/shipment.rb
> +  belongs_to :collectivity
Est-ce qu'on est capable de renseigner à la main les quelques références hubee qui manquent en prod avec de la vraie data qu'on irait lire dans hubee avec nos yeux d'humains ?

2024-07-08 14:43 UTC, JeSuisUnCaillou commented on db/migrate/20240704131031_add_collectivity_id_to_shipments.rb
> +    add_reference :shipments, :collectivity, foreign_key: true
Effectivement, je viens de tester.

2024-07-09 07:57 UTC, jbfeldis approved these changes

2024-07-09 07:57 UTC, merged