Only show active collectivities
etalab/formulaire-qf pull request #83
Opened 2024-07-11 15:33 UTC by JeSuisUnCaillou

2024-07-15 09:51 UTC, jbfeldis requested changes

2024-07-15 09:51 UTC, jbfeldis commented on app/controllers/collectivities_controller.rb
> +      text: t(".not_found_error.text"),
Il manque le siret en argument ici

2024-07-15 09:55 UTC, JeSuisUnCaillou commented on app/controllers/collectivities_controller.rb
> +      text: t(".not_found_error.text"),
bien vu !

2024-07-29 10:34 UTC, jbfeldis approved these changes

2024-07-29 13:48 UTC, merged